hmcts/em-native-pdf-annotator-app

src/main/java/uk/gov/hmcts/reform/em/npa/service/impl/AnnotationSetDTOToPDAnnotationMapperImpl.java

https://tools.hmcts.net/jira/browse/EM-757
```
[ ] Yes
[ X] No
```

Add property to show hidelight in PDF reader

---

src/main/java/uk/gov/hmcts/reform/em/npa/config/SwaggerConfiguration.java
src/main/java/uk/gov/hmcts/reform/em/npa/rest/DocumentTaskResource.java

add swagger docs 
```
[ ] Yes
[x] No
```

Add Swaggerdocs to DocumentTaskResource

---

Dockerfile
Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
build.gradle
dependency-check-suppressions.xml
gradle/wrapper/gradle-wrapper.properties
infrastructure/application-insights.tf
infrastructure/main.tf
infrastructure/variables.tf
kubernetes/config.aat.yaml
kubernetes/config.saat.yaml
kubernetes/deployment.template.yaml

Embed AKS into the pipeline. Follows the same steps that em-anno-api did.
```
[ ] Yes
[ ] No
```

Embed AKS to the Jenkins pipeline

---

Jenkinsfile_nightly

Changed JenkinsfileNightly product variable from "anno" to "npa"
```
[ ] Yes
[x] No
```

corrected product variable in nightly Jenkins file

---

Dockerfile
build.gradle

EM-1288
```
[ ] Yes
[x] No
```

upgrade CNP dependencies

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
build.gradle
docker-compose-dependencies.yml
infrastructure/aat.tfvars
infrastructure/demo.tfvars
infrastructure/main.tf
infrastructure/output.tf
infrastructure/preview.tfvars
infrastructure/prod.tfvars
infrastructure/saat.tfvars
infrastructure/variables.tf
src/aat/java/uk/gov/hmcts/reform/em/npa/functional/DocumentTaskScenarios.java
src/aat/java/uk/gov/hmcts/reform/em/npa/performance/HttpConfiguration.scala
src/aat/java/uk/gov/hmcts/reform/em/npa/performance/NpaLoad.scala
src/aat/java/uk/gov/hmcts/reform/em/npa/testutil/Env.java
src/aat/java/uk/gov/hmcts/reform/em/npa/testutil/IdamHelper.java
src/aat/java/uk/gov/hmcts/reform/em/npa/testutil/S2sHelper.java
src/aat/java/uk/gov/hmcts/reform/em/npa/testutil/TestUtil.java
src/main/java/uk/gov/hmcts/reform/em/npa/domain/DocumentTask.java
src/main/java/uk/gov/hmcts/reform/em/npa/domain/EntityAuditEvent.java
src/main/java/uk/gov/hmcts/reform/em/npa/domain/PersistentAuditEvent.java
src/main/resources/application-aat.yaml
src/main/resources/application.yaml
src/main/resources/liquibase.properties

[PREVIEW] Sidam

---

charts/em-npa/Chart.yaml
charts/em-npa/values.template.yaml

DB name was changed, but Env Var for DB URL wasn't. This updates DB URL Env Var
```
[ ] Yes
[ ] No
```

correct db name

---

charts/em-npa/values.yaml

try to pass env vars into product chart's microservice pod properly
```
[ ] Yes
[ ] No
```

helm-datasource-in-quotes

---

charts/em-npa/requirements.yaml
charts/em-npa/values.aat.template.yaml
charts/em-npa/values.preview.template.yaml
charts/em-npa/values.yaml

helm remove aliases

---

charts/em-npa/Chart.yaml
charts/em-npa/requirements.yaml
charts/em-npa/values.aat.template.yaml
charts/em-npa/values.preview.template.yaml
charts/em-npa/values.yaml

revert attempted DM Store-bug bugfixing
```
[ ] Yes
[x] No
```

helm re-add alias

---

charts/em-npa/Chart.yaml
charts/em-npa/requirements.yaml
charts/em-npa/values.yaml

helm increase healthchck delay times

---

charts/em-npa/values.yaml

helm hit liveness

---

Jenkinsfile_CNP
dependency-check-suppressions.xml

Stop deploying to prod
```
[ ] Yes
[ ] No
```

stop deploying to prod

---

charts/em-npa/Chart.yaml
infrastructure/main.tf
infrastructure/output.tf

https://tools.hmcts.net/jira/browse/EM-2032
Replaced the vault_uri with key_vault_id

Replaced the vault_uri with key_vault_id

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
charts/em-npa/Chart.yaml
charts/em-npa/values.aat.template.yaml
charts/em-npa/values.preview.template.yaml
charts/em-npa/values.yaml
dependency-check-suppressions.xml
infrastructure/aat.tfvars
infrastructure/main.tf
infrastructure/preview.tfvars
infrastructure/prod.tfvars
infrastructure/sprod.tfvars
infrastructure/variables.tf
src/main/resources/bootstrap.yaml

EM-2111: Prepare npa for AKS migration

---

infrastructure/main.tf

EM-2111: Fix DB name to reflect recent changes

---

infrastructure/main.tf

fix tf dependency

---

Jenkinsfile_CNP

disable Legacy Deployment On AAT

---

infrastructure/main.tf

disable ASE

---

charts/em-npa/Chart.yaml
charts/em-npa/requirements.yaml
charts/em-npa/values.aat.template.yaml
charts/em-npa/values.preview.template.yaml
charts/em-npa/values.yaml

https://tools.hmcts.net/jira/browse/EM-2254

Removed alias related lines

---

charts/em-npa/Chart.yaml
charts/em-npa/values.preview.template.yaml

indent postgres & bump chart ver

---

dependency-check-suppressions.xml

Suppressed vulnerability

---

Jenkinsfile_CNP
charts/em-npa/values.preview.template.yaml
dependency-check-suppressions.xml

add supps.

---

infrastructure/main.tf

remove ase code from infra

---

charts/em-npa/Chart.yaml
charts/em-npa/requirements.yaml
dependency-check-suppressions.xml

update java chart

---

dependency-check-suppressions.xml

test PR add suppressions

---

build.gradle

revert dependabot problem spring web upgd

---

build.gradle
src/main/java/uk/gov/hmcts/reform/em/npa/rest/errors/ErrorConstants.java
src/main/java/uk/gov/hmcts/reform/em/npa/rest/errors/ExceptionTranslator.java
src/test/java/uk/gov/hmcts/reform/em/npa/rest/errors/ExceptionTranslatorIntTest.java

Resolved the zalando dependency issue

Resolved the zalando dependency issue

---

Jenkinsfile_CNP
charts/em-npa/Chart.yaml
charts/em-npa/values.yaml
src/main/java/uk/gov/hmcts/reform/em/npa/config/security/SecurityConfiguration.java

Removed issuer validation

---

bin/idam-authenticate.sh
bin/idam-client-setup.sh
bin/start-local-environment.sh
docker-compose-dependencies.yml

Added in startup script

---

build.gradle
src/main/java/uk/gov/hmcts/reform/em/npa/config/Config.java
src/main/java/uk/gov/hmcts/reform/em/npa/config/security/SecurityUtils.java
src/main/java/uk/gov/hmcts/reform/em/npa/config/security/SpringSecurityAuditorAware.java
src/main/java/uk/gov/hmcts/reform/em/npa/repository/IdamRepository.java
src/main/java/uk/gov/hmcts/reform/em/npa/service/impl/DmStoreUploaderImpl.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/em/npa/config/security/SecurityUtilsTest.java
src/test/java/uk/gov/hmcts/reform/em/npa/rest/DocumentTaskResourceIntTest.java

User id fix

---

build.gradle
src/main/java/uk/gov/hmcts/reform/em/npa/redaction/ImageRedaction.java
src/main/java/uk/gov/hmcts/reform/em/npa/redaction/PdfRedaction.java
src/main/java/uk/gov/hmcts/reform/em/npa/service/DmStoreUploader.java
src/main/java/uk/gov/hmcts/reform/em/npa/service/RedactionService.java
src/main/java/uk/gov/hmcts/reform/em/npa/service/dto/external/redaction/RedactionDTO.java
src/main/java/uk/gov/hmcts/reform/em/npa/service/impl/DmStoreUploaderImpl.java
src/main/java/uk/gov/hmcts/reform/em/npa/service/impl/FileTypeException.java
src/main/java/uk/gov/hmcts/reform/em/npa/service/impl/RedactionProcessingException.java
src/main/java/uk/gov/hmcts/reform/em/npa/service/impl/RedactionServiceImpl.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/EM-2792
Added in logic to download and upload redacted file

Em 2792 persist readacted doc

---

Jenkinsfile_CNP
build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/EM-2884
Added Pact Test to build pipeline
```
[ ] Yes
[ X ] No
```

EM-2884 Added pipeline configurations for PactTest

---

Jenkinsfile_CNP
build.gradle
dependency-check-suppressions.xml
pacts/npa_api-idam_api.json
src/contractTest/java/uk/gov/hmcts/reform/em/npa/IdamConsumerTest.java

Em 2884 integrate pact test in pipeline

---

Jenkinsfile_CNP
Jenkinsfile_parameterized
README.md
build.gradle
src/aat/java/uk/gov/hmcts/reform/em/npa/functional/DocumentTaskScenarios.java
src/aat/java/uk/gov/hmcts/reform/em/npa/functional/OpenIdConnectScenarios.java

EM-2721 : Serenity Reporting for NPA

EM-2721 : Serenity Reporting for NPA

---

build.gradle
dependency-check-suppressions.xml

EM-2721 : NPA Serenity Single page reports.

EM-2721 : NPA Serenity Single page reports.

---

build.gradle
dependency-check-suppressions.xml
pacts/npa_api-idam_api.json
src/contractTest/java/uk/gov/hmcts/reform/em/npa/IdamConsumerTest.java

https://tools.hmcts.net/jira/browse/EM-2884
Fix for POST request body generation in pact json
Added few serenity report changes
```
[ ] Yes
[X ] No
```

EM-2884 request body generation in pact json

---

src/main/resources/db/changelog/00000000000000_initial_schema.xml
src/main/resources/db/db.changelog-master.xml

Reverted hibernate_sequence change

Reverted hibernate_sequence change

---

Jenkinsfile_CNP
dependency-check-suppressions.xml

remove in cht

---

README.md
dependency-check-suppressions.xml

Update README to remove hmcts spring template content and update setup

---

src/main/resources/application.yaml

Add XUI to S2S whitelist

---

Jenkinsfile_CNP
dependency-check-suppressions.xml
src/main/java/uk/gov/hmcts/reform/em/npa/config/SwaggerConfiguration.java

Update Jenkinsfile for swagger

---

build.gradle
dependency-check-suppressions.xml

EM-2976: Add library to fix issue with jbig2 images

---

src/main/java/uk/gov/hmcts/reform/em/npa/config/SwaggerConfiguration.java

Added Auth & Service Auth as global headers

Updated Swagger doc

---

build.gradle
src/main/java/uk/gov/hmcts/reform/em/npa/config/security/SecurityUtils.java
src/main/java/uk/gov/hmcts/reform/em/npa/repository/IdamRepository.java
src/test/java/uk/gov/hmcts/reform/em/npa/repository/IdamRepositoryTest.java

Updated em-test-helper version and changed the userdetails endpoint

Updated em-test-helper version and changed the userdetails endpoint

---

src/main/java/uk/gov/hmcts/reform/em/npa/config/SwaggerConfiguration.java
src/main/java/uk/gov/hmcts/reform/em/npa/rest/DocumentTaskResource.java

Updated Swagger version

---

idam-client-setup.sh

Added file

---

src/main/java/uk/gov/hmcts/reform/em/npa/service/impl/RedactionServiceImpl.java

EM-2671: Convert all file extensions to lower case before checking them

---

Dockerfile
build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/EM-3004

Em 3004 java11 upgrade 2

---

Jenkinsfile_nightly

https://tools.hmcts.net/jira/browse/EM-3074

Updated nightly build file

---

Jenkinsfile_nightly
build.gradle

https://tools.hmcts.net/jira/browse/EM-2554

Added in changes for Mutation test

---

dependency-check-suppressions.xml
infrastructure/aat.tfvars
infrastructure/main.tf

Updated MI

---

build.gradle
dependency-check-suppressions.xml

Updated owasp version

---

audit.json

EM-3238 -NPA API : Investigate NPA api failing nightly build jobs

---

infrastructure/aat.tfvars
infrastructure/perftest.tfvars
infrastructure/prod.tfvars
infrastructure/variables.tf

Removed mi value for env tf files

Removed mi value for env tf files

---

build.gradle
src/aat/java/uk/gov/hmcts/reform/em/npa/functional/DocumentTaskScenarios.java
src/aat/java/uk/gov/hmcts/reform/em/npa/functional/MarkUpScenarios.java
src/aat/java/uk/gov/hmcts/reform/em/npa/functional/OpenIdConnectScenarios.java
src/aat/java/uk/gov/hmcts/reform/em/npa/functional/RedactionScenarios.java

EM-3260 - NPA API : Add retry logic for failing functional test cases

---

build.gradle

https://tools.hmcts.net/jira/browse/EM-3303

Resolved vulnerability

---

build.gradle

EM-3429 - EM-NPA: Failed to generate serenity report

---

charts/em-npa/Chart.yaml
charts/em-npa/values.yaml

Added in flux test var

---

infrastructure/main.tf
infrastructure/variables.tf
src/main/resources/bootstrap.yaml

https://tools.hmcts.net/jira/browse/EM-3476

Added postgres v11 details

---

infrastructure/main.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/EM-3476

Updated postgres v11 details

---

build.gradle

EM-3510- Check & Update PACT/Jupiter Unit tests related Dependencies

---

audit.json

EM-3519 - suppress security scan error

---

build.gradle
config/owasp/dependency-check-suppressions.xml

Resolved CVE-2021-25122, CVE-2021-25329

---

README.md
docker-compose-dependencies-simulator.yml
src/aat/java/uk/gov/hmcts/reform/em/npa/functional/DocumentTaskScenarios.java

https://tools.hmcts.net/jira/browse/EM-3585
```
[ ] Yes
[X] No
```

Updated docker to use rse-idam-simulator

---

src/aat/java/uk/gov/hmcts/reform/em/npa/functional/RedactionScenarios.java
src/aat/java/uk/gov/hmcts/reform/em/npa/testutil/TestUtil.java

EM-3555-EM-NPA api: Add functional test cases for RedactionResource

---

src/aat/java/uk/gov/hmcts/reform/em/npa/functional/MarkUpScenarios.java
src/aat/java/uk/gov/hmcts/reform/em/npa/testutil/TestUtil.java

EM-3602 - EM-NPA api: Add functional test cases for MarkUpResource

---

src/main/java/uk/gov/hmcts/reform/em/npa/info/BuildInfo.java

https://tools.hmcts.net/jira/browse/EM-3754
Fixed Resource leak
```
[ ] Yes
[X] No
```

Fixed Resource leak

---

build.gradle

Added junit 5 plugin to fix mutation tests on pipeline
```
[ ] Yes
[x] No
```

added junit 5 plugin

---

audit.json

Fixing nightly build
```
[ ] Yes
[ x] No
```

added another cookie

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/EM-3476
Updated name, product, component in db details
```
[ ] Yes
[X] No
```

Updated name, product, component in db details

---

build.gradle

Fixing nightly
```
[ ] Yes
[x] No
```

reverting dependabot changes

---

build.gradle
src/main/java/uk/gov/hmcts/reform/em/npa/config/Constants.java
src/main/java/uk/gov/hmcts/reform/em/npa/info/BuildInfo.java
src/main/java/uk/gov/hmcts/reform/em/npa/rest/MarkUpResource.java
src/main/java/uk/gov/hmcts/reform/em/npa/rest/RedactionResource.java
src/test/java/uk/gov/hmcts/reform/em/npa/info/BuildInfoTest.java
src/test/java/uk/gov/hmcts/reform/em/npa/rest/MarkUpResourceTest.java
src/test/java/uk/gov/hmcts/reform/em/npa/rest/RedactionResourceTest.java

https://tools.hmcts.net/jira/browse/EM-3754
Fixed Mass Assignment: Insecure Binder Configuration issue
```
[ ] Yes
[X] No
```

Fixed Mass Assignment: Insecure Binder Configuration issue

---

build.gradle

Verifying mutation test failures with latest plugin
https://tools.hmcts.net/jira/browse/DTSPO-3448
trying to fix mutation testing and build passing in PR
https://build.platform.hmcts.net/view/Evidence/job/HMCTS_Nightly_EM/job/em-native-pdf-annotator-app/job/fix-mutation-test/
```
[ ] Yes
[x] No
```

fix mutation plugin

---

build.gradle

N/A
Removed binary url
```
[ ] Yes
[X] No
```

Removed binary url

---

Jenkinsfile_nightly
build.gradle
config/fortify-client.properties
src/test/resources/logback.xml

https://tools.hmcts.net/jira/browse/EM-3958
Added in fortify library
```
[ ] Yes
[X] No
```

Added in fortify library

---

build.gradle
src/main/java/uk/gov/hmcts/reform/em/npa/Application.java
src/main/java/uk/gov/hmcts/reform/em/npa/config/ServiceTokenGeneratorConfiguration.java
src/main/java/uk/gov/hmcts/reform/em/npa/config/security/SecurityUtils.java
src/main/java/uk/gov/hmcts/reform/em/npa/service/ServiceNameAspect.java
src/test/java/uk/gov/hmcts/reform/em/npa/service/ServiceNameAspectTest.java

https://tools.hmcts.net/jira/browse/EM-3973
Added in logging to capture the consuming service name
```
[ ] Yes
[X] No
```

Added in logging to capture the consuming service name

---

charts/em-npa/Chart.yaml

https://tools.hmcts.net/jira/browse/EM-3994
Updated Chart Java version
```
[ ] Yes
[X] No
```

Updated Chart Java version

---

audit.json
security.sh

https://tools.hmcts.net/jira/browse/EM-4027
- em-native-pdf-annotator-api security scan Fix
```
[ ] Yes
[x ] No
```

EM-4027-SecurityScanFix

---

audit.json

https://tools.hmcts.net/jira/browse/EM-4047
Nightly Pipeline fix
```
[ ] Yes
[x ] No
```

EM-4047-NightlyPipeline Fix

---

infrastructure/state.tf

https://tools.hmcts.net/jira/browse/EM-4048
terraform provider patch
```
[ ] Yes
[x] No
```

terraform provider patch

---

infrastructure/main.tf
infrastructure/state.tf

EM-4048: terraform provider patch
EM-4048: terraform provider patch
```
[ ] Yes
[x] No
```

EM-4048: terraform provider patch

---

infrastructure/main.tf
infrastructure/state.tf

EM-4048
EM-4048-terraform-provider
```
[ ] Yes
[x] No
```

EM-4048-terraform-provider fix

---

infrastructure/state.tf

Update azuread version

---

infrastructure/application-insights.tf
infrastructure/main.tf
infrastructure/state.tf

https://tools.hmcts.net/jira/browse/DTSPO-4926
Fixed TF 0.15 compatibility issues.
```
[ ] Yes
[X] No
```

Fixed TF 0.15 compatibility issues.

---

audit.json

https://tools.hmcts.net/jira/browse/EM-4057
em-native-pdf-annotator-app
Nightly Pipeline fix
```
[ ] Yes
[x ] No
```

EM-4057-SecurityScan Fix

---

src/aat/java/uk/gov/hmcts/reform/em/npa/functional/MarkUpScenarios.java
src/main/java/uk/gov/hmcts/reform/em/npa/appinsights/AppInsightsEventRepository.java
src/main/java/uk/gov/hmcts/reform/em/npa/config/security/SpringSecurityAuditorAware.java
src/main/java/uk/gov/hmcts/reform/em/npa/domain/EntityAuditEvent.java
src/main/java/uk/gov/hmcts/reform/em/npa/redaction/PdfRedaction.java
src/main/java/uk/gov/hmcts/reform/em/npa/service/dto/external/annotation/RectangleDTO.java
src/main/java/uk/gov/hmcts/reform/em/npa/service/mapper/EntityMapper.java
src/main/java/uk/gov/hmcts/reform/em/npa/service/mapper/RectangleMapper.java
src/test/java/uk/gov/hmcts/reform/em/npa/rest/RedactionResourceTest.java
src/test/java/uk/gov/hmcts/reform/em/npa/service/impl/MarkUpServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/em/npa/service/impl/RedactionServiceImplTest.java

N/A
Fixed checkstyle errors
```
[ ] Yes
[X] No
```

Fixed checkstyle errors

---

src/main/java/uk/gov/hmcts/reform/em/npa/service/ServiceNameAspect.java
src/test/java/uk/gov/hmcts/reform/em/npa/service/ServiceNameAspectTest.java

https://tools.hmcts.net/jira/browse/EM-4065
Resolve Error status with code : 500 for ServiceNameAspect
```
[ ] Yes
[X] No
```

Add InvalidTokenException to ServiceNameAspect and its test class

---

build.gradle
config/owasp/dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/EM-4186
Fixed log4J vulnerability
```
[ ] Yes
[X] No
```

Fixed log4J vulnerability

---

build.gradle

https://tools.hmcts.net/jira/browse/EM-4188
Updated log4j version
```
[ ] Yes
[X] No
```

Updated log4j version

---

build.gradle
src/main/java/uk/gov/hmcts/reform/em/npa/rest/errors/BadRequestAlertException.java
src/main/java/uk/gov/hmcts/reform/em/npa/rest/errors/CustomParameterizedException.java
src/main/java/uk/gov/hmcts/reform/em/npa/rest/util/HeaderUtil.java

https://tools.hmcts.net/jira/browse/EM-4172
Updated sonar config
```
[ ] Yes
[X] No
```

Updated sonar config

---

src/main/java/uk/gov/hmcts/reform/em/npa/rest/RedactionResource.java
src/main/java/uk/gov/hmcts/reform/em/npa/service/impl/DmStoreDownloaderImpl.java

https://tools.hmcts.net/jira/browse/EM-4172
Fix SonarQube issues
```
[ ] Yes
[X] No
```

Fix sonar issues

---

gradle/wrapper/gradle-wrapper.properties

https://tools.hmcts.net/jira/browse/EM-4223
Upgrade gradle to 7.3.3
```
[ ] Yes
[X] No
```

Upgrade gradle to 7.3.3

---

bin/start-local-environment.sh
docker-compose-dependencies.yml
src/aat/resources/application.yml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/EM-4226
Added in am-role-assignment-service docker dependency
```
[ ] Yes
[X] No
```

Added in am-role-assignment-service docker dependency

---

build.gradle

https://tools.hmcts.net/jira/browse/EM-4264
Fix CVE-2021-44832, CVE-2021-42550, CVE-2022-23181
```
[ ] Yes
[X] No
```

Resolve CVE's

---

charts/em-npa/Chart.yaml

https://tools.hmcts.net/jira/browse/EM-4268
Update helm chart
```
[ ] Yes
[X] No
```

Update helm chart

---

config/owasp/dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/EM-4275
Removed suppressions
```
[ ] Yes
[X] No
```

Removed suppressions

---

database/Dockerfile
docker-compose-dependencies.yml

https://tools.hmcts.net/jira/browse/EM-4290
update postgres version to 11 for local setup
```
[ ] Yes
[X] No
```

update postgres version to 11 for local setup

---

charts/em-npa/Chart.yaml

bump java chart
```
[ ] Yes
[X] No
```

bump java chart

---

build.gradle
src/main/java/uk/gov/hmcts/reform/em/npa/Application.java
src/main/java/uk/gov/hmcts/reform/em/npa/config/SwaggerConfiguration.java
src/main/java/uk/gov/hmcts/reform/em/npa/config/security/SecurityConfiguration.java
src/main/java/uk/gov/hmcts/reform/em/npa/rest/MarkUpResource.java
src/main/java/uk/gov/hmcts/reform/em/npa/rest/RedactionResource.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/EM-4300
Upgraded SpringBoot version to 2.6.4
```
[ ] Yes
[X] No
```

Upgraded SpringBoot version to 2.6.4

---

audit.json

Native PDF Annotator Security Scan fix
```
[ ] Yes
[x ] No
```

[EM-4310]-Native PDF Annotator Security Scan fix

---

src/main/java/uk/gov/hmcts/reform/em/npa/domain/PersistentAuditEvent.java
src/main/resources/db/changelog/00000000000000_initial_schema.xml

https://tools.hmcts.net/jira/browse/EM-4320
Updated column name to resolve reserve word issue
```
[ ] Yes
[X] No
```

Updated column name to resolve reserve word issue

---

.github/dependabot.yml

EM-4335 - disable dependabot for libraries

---

build.gradle
src/main/java/uk/gov/hmcts/reform/em/npa/rest/util/HeaderUtil.java
src/test/java/uk/gov/hmcts/reform/em/npa/service/impl/DmStoreDownloaderImplTest.java

https://tools.hmcts.net/jira/browse/EM-4389
Check and update the exclusion list of Sonar Coverage Classes
```
[ ] Yes
[X] No
```

EM-4389: Update the sonar exclusions

---

audit.json

https://tools.hmcts.net/jira/browse/EM-4412
Fix security scan by adding ignore for 13 alerts
```
[ ] Yes
[x] No
```

Ignore alerts

---

README.md
build.gradle
src/aat/java/uk/gov/hmcts/reform/em/npa/functional/RedactionScenarios.java
src/aat/java/uk/gov/hmcts/reform/em/npa/testutil/ExtendedCcdHelper.java
src/aat/java/uk/gov/hmcts/reform/em/npa/testutil/TestUtil.java

https://tools.hmcts.net/jira/browse/EM-4428
Updated test username to resolve the issue.
```
[ ] Yes
[X] No
```

Fixed build failure

---

audit.json

https://tools.hmcts.net/jira/browse/EM-4419
Fix security scan by adding ignores
```
[ ] Yes
[x] No
```

Add ignores for 4 alerts relating to markups/?pageable=_GET

---

audit.json

Em-native-pdf-annotator Security Scan Fix
```
[ ] Yes
[ x] No
```

[EM-4333]-Security Scan Fix

---

src/main/resources/db/changelog/00000000000000_initial_schema.xml

https://tools.hmcts.net/jira/browse/EM-4436
Updated column size for principal
```
[ ] Yes
[X] No
```

Updated column size for principal

---

build.gradle

https://tools.hmcts.net/jira/browse/EM-4462
Fix CVE issue caused by springboot starter security
```
[ ] Yes
[x] No
```

Exclude springboot-starter-security

---

bin/idam/idam.sh
bin/start-local-environment.sh
docker-compose-dependencies-simulator.yml
docker-compose-dependencies.yml
src/aat/resources/application.yml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/EM-4470
Updated local S2S & IDAM port
```
[ ] Yes
[X] No
```

Updated local S2S & IDAM port

---

build.gradle
settings.gradle
src/aat/resources/application.yml
src/cftlib/java/uk/gov/hmcts/reform/em/npa/redaction/cftlib/CftLibConfig.java
src/main/resources/application.yaml
src/main/resources/cftlib-am-role-assignments.json

https://tools.hmcts.net/jira/browse/EM-4470
Added in changes for CFTLib
```
[ ] Yes
[X] No
```

Added in changes for CFTLib

---

build.gradle
config/owasp/dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/EM-4515
Removed redundant cve suppression
```
[ ] Yes
[X] No
```

Removed redundant cve suppression

---

src/main/java/uk/gov/hmcts/reform/em/npa/service/ServiceNameAspect.java

https://tools.hmcts.net/jira/browse/EM-4560
Resolve service exception
```
[ ] Yes
[x] No
```

Resolve service exception

---

charts/em-npa/Chart.yaml
charts/em-npa/values.preview.template.yaml
charts/em-npa/values.yaml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/EM-4532
Resolved fortify preview secret issue
```
[ ] Yes
[X] No
```

Resolved fortify preview secret issue

---

infrastructure/main.tf
infrastructure/perftest.tfvars
infrastructure/prod.tfvars
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/EM-4565
Increased DB storage size for Perftest & Prod.
```
[ ] Yes
[X] No
```

Increased DB storage size for Perftest & Prod

---

.github/dependabot.yml
.github/renovate.json
.github/stale.yml
renovate.json

https://tools.hmcts.net/jira/browse/EM-4567
Added in dependabot config
```
[ ] Yes
[X] No
```

Added in dependabot config

---

Dockerfile

EM-4606 copy app-insight json

---

build.gradle

fix nightly build,
fix pitest and avoid CVE-2022-40149, CVE-2022-40150

fix nightly build

---

build.gradle

EM-4607 vulnerability jettison
avoid CVE-2022-40149, CVE-2022-40150

EM-4607 vulnerability jettison

---

Dockerfile

[EM-4680](https://tools.hmcts.net/jira/browse/EM-4666) upgrade appinsight jar

EM-4680 upgrade appinsight jar

---

README.md
build.gradle
src/test/resources/config/application.yaml

https://tools.hmcts.net/jira/browse/EM-4706
Use postgres test db
```
[ ] Yes
[x] No
```

Use postgres test db

---

build.gradle

https://tools.hmcts.net/jira/browse/EM-4813
Updated fileway core to 9.0.4
```
[ ] Yes
[ ] No
```

EM-4813: Updated fileway core to 9.0.4

---

src/main/java/uk/gov/hmcts/reform/em/npa/redaction/PdfRedaction.java

https://tools.hmcts.net/jira/browse/EM-4801
Reduced dpi to 200 to investigate SSCS scanned doc issue.
```
[ ] Yes
[X] No
```

Fix for Redaction in Scanned Doc from Exela

---

build.gradle

[EM-4684](https://tools.hmcts.net/jira/browse/EM-4684) remove auth-checker

EM-4684 remove auth-checker

---

build.gradle
config/owasp/dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/EM-5177
Updated CVE List.
```
[ ] Yes
[X] No
```

Updated CVE List

---

security.sh

EM-5186 remove security.sh

---

audit.json

EM-5198 suppress sec vul

---

build.gradle

EM-5116 bump spring cloud

---

src/main/java/uk/gov/hmcts/reform/em/npa/service/EmCaseDocumentClientApi.java

EM-5116 getting ready for spring upgrade, remove unused class

 EM-5116 remove unused class

---

build.gradle
src/aat/java/uk/gov/hmcts/reform/em/npa/smoke/SmokeTest.java

Em-5116 arrange cloud libs

---

build.gradle

bump serenity

---

build.gradle
src/test/java/uk/gov/hmcts/reform/em/npa/rest/errors/ExceptionTranslatorIntTest.java

Em-5116 remove javax libs and fix test

Em-5116 remove javax libs and fix test

---

src/test/java/uk/gov/hmcts/reform/em/npa/config/audit/AsyncEntityAuditEventWriterTest.java
src/test/java/uk/gov/hmcts/reform/em/npa/redaction/ImageRedactionTest.java
src/test/java/uk/gov/hmcts/reform/em/npa/redaction/PdfRedactionTest.java
src/test/java/uk/gov/hmcts/reform/em/npa/service/impl/DmStoreDownloaderImplTest.java

Em-5116 remove spring boot tests `SpringBootTest` and refactor tests

Em-5116 remove spring boot tests and refactor test

---

charts/em-npa/Chart.yaml
charts/em-npa/values.yaml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/EM-5280
Updated service whitelist for all non-prod environments.
```
[ ] Yes
[X] No
```

Updated service whitelist

---

build.gradle

Em-5116 refactor serenity plugin

Em-5116 refactor serenity plugin

---

charts/em-npa/Chart.yaml
charts/em-npa/values.yaml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/EM-5390
Updated DB Connection Pool Size to resolve the DB Connection issue on Prod.
```
[ ] Yes
[X] No
```

Updated DB Connection Pool Size

---

charts/em-npa/Chart.yaml
charts/em-npa/values.yaml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/EM-5405
Updated Hikari connection-timeout & Removed redundant tomcat attributes.
```
[ ] Yes
[X] No
```

Updated Hikari connection-timeout

---

src/aat/java/uk/gov/hmcts/reform/em/npa/functional/MarkUpScenarios.java
src/main/java/uk/gov/hmcts/reform/em/npa/rest/MarkUpResource.java
src/test/java/uk/gov/hmcts/reform/em/npa/rest/MarkUpResourceTest.java

https://tools.hmcts.net/jira/browse/EM-5417
respond with 204 when no markups
```
[ ] Yes
[x] No
```

change response code

---

audit.json

https://tools.hmcts.net/jira/browse/EM-5487
added 1 fingerprint to audit.json

em-5487: added 1 fingerprint to audit.json

---

infrastructure/main.tf
infrastructure/variables.tf

Added in v14 db config.
```
[ ] Yes
[X] No
```

Added in v14 db config

---

Jenkinsfile_CNP

Disable Demo branch sync for Postgres FlexiServer setup.
```
[ ] Yes
[X] No
```

Disable Demo branch sync

---

build.gradle
infrastructure/main.tf
infrastructure/variables.tf

Updated sku & storage.
```
[ ] Yes
[X] No
```

Updated sku & storage

---

infrastructure/main.tf
infrastructure/variables.tf

Added in v14 db config for perftest.
```
[ ] Yes
[X] No
```

Added in v14 db config for perftest

---

infrastructure/main.tf
infrastructure/variables.tf

Added in v14 db config for ithc.
```
[ ] Yes
[X] No
```

Added in v14 db config for ithc

---

infrastructure/main.tf
infrastructure/variables.tf

Added in v14 db config for aat & prod.
```
[ ] Yes
[X] No
```

Added in v14 db config for aat & prod

---

src/main/java/uk/gov/hmcts/reform/em/npa/redaction/PdfRedaction.java

https://tools.hmcts.net/jira/browse/EM-5479
log format error
```
[ ] Yes
[x] No
```

log format error

---

Jenkinsfile_CNP
infrastructure/main.tf

Reverted v14 DB changes to resolve sequence issue.
```
[ ] Yes
[X] No
```

Reverted v14 DB changes

---

config/owasp/dependency-check-suppressions.xml

EM-5616 suppress vulnerability

EM-5616 suppress vulnerability

---

lib/applicationinsights.json

EM-5505 reduce app-insight logs
log less health logs

EM-5505 reduce app-insight logs

---

build.gradle
config/owasp/dependency-check-suppressions.xml

EM-5636 avoid vulnerabilities

---

build.gradle

Reverts hmcts/em-native-pdf-annotator-app#1720

Revert "Update plugin org.flywaydb.flyway to v10"

---

Dockerfile

EM-5649 fix app-insight logging

EM-5649 fix app-insight logging

---

src/main/java/uk/gov/hmcts/reform/em/npa/batch/EntityValueProcessor.java
src/main/java/uk/gov/hmcts/reform/em/npa/domain/EntityAuditEvent.java
src/main/resources/db/migration/V6__drop_entity_value.sql

https://tools.hmcts.net/jira/browse/EM-5665
drop old entity value column

drop old entity value column

---

build.gradle
charts/em-npa/Chart.yaml
charts/em-npa/values.preview.template.yaml
src/main/java/uk/gov/hmcts/reform/em/npa/batch/RemoveLargeObjectsTasklet.java
src/main/java/uk/gov/hmcts/reform/em/npa/config/BatchConfiguration.java
src/main/java/uk/gov/hmcts/reform/em/npa/repository/LargeObjectRepository.java

https://tools.hmcts.net/jira/browse/EM-5665
add tasklet to remove large objects

add tasklet to remove large objects

---

build.gradle
config/owasp/dependency-check-suppressions.xml

EM-5717 arrange dependency management

EM-5717 arrange dependency management

---

charts/em-npa/Chart.yaml
charts/em-npa/values.yaml
infrastructure/main.tf

Updated v15 DB default config.

Updated v15 DB default config

---

infrastructure/main.tf
infrastructure/perftest.tfvars
infrastructure/prod.tfvars
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/EM-5624
Removed v11 DB related config.

Removed v11 DB related config

---

build.gradle

https://tools.hmcts.net/jira/browse/EM-5722
use buildscript for flyway postgresql

use buildscript for flyway postgresql

---

src/main/java/uk/gov/hmcts/reform/em/npa/rest/RedactionResource.java
src/main/java/uk/gov/hmcts/reform/em/npa/service/impl/RedactionServiceImpl.java

https://tools.hmcts.net/jira/browse/EM-5743
investigate redact issue

Em 5743 investigate redact issue

---

build.gradle

https://tools.hmcts.net/jira/browse/EM-5795
Migrating to java 21, making needed changes to the repo associated with this change.

EM-5795 migrating to java 21

---

src/main/java/uk/gov/hmcts/reform/em/npa/config/security/SecurityConfiguration.java

https://tools.hmcts.net/jira/browse/EM-5805
update deprecated security config

update deprecated config

---

config/owasp/dependency-check-suppressions.xml

EM-5836 extend owasp suppression

---

src/main/java/uk/gov/hmcts/reform/em/npa/redaction/PdfRedaction.java
src/main/java/uk/gov/hmcts/reform/em/npa/repository/IdamRepository.java
src/main/java/uk/gov/hmcts/reform/em/npa/rest/MarkUpResource.java
src/main/java/uk/gov/hmcts/reform/em/npa/rest/WelcomeResource.java
src/main/java/uk/gov/hmcts/reform/em/npa/service/CdamService.java
src/test/java/uk/gov/hmcts/reform/em/npa/service/CdamServiceTest.java

https://tools.hmcts.net/jira/browse/EM-5916
Fixed high and medium severity code smells, left the smells in PdfRedaction and RedactionServiceImpl as these will be re-enabled in future and are only disabled for troubleshooting.

Fixing High and medium severity code smells. 

---

config/owasp/dependency-check-suppressions.xml

EM-5940-extend-suppression

---

charts/em-npa/Chart.yaml

revert java chart upgrade

---

charts/em-npa/Chart.yaml
charts/em-npa/values.yaml

https://tools.hmcts.net/jira/browse/EM-5973

Enable spot instances for lower envs

---

charts/em-npa/Chart.yaml
charts/em-npa/values.yaml

https://tools.hmcts.net/jira/browse/EM-5973

Moved spot instances out from environment

---

charts/em-npa/Chart.yaml
charts/em-npa/values.yaml

https://tools.hmcts.net/jira/browse/EM-5989
Disabled Spot instances.

Disabled Spot instances

---

infrastructure/state.tf

Reverts hmcts/em-native-pdf-annotator-app#2041
https://tools.hmcts.net/jira/browse/EM-6041

Revert "Update Terraform azurerm to ~> 3.105.0"

---

src/main/java/uk/gov/hmcts/reform/em/npa/config/audit/AsyncEntityAuditEventWriter.java
src/main/java/uk/gov/hmcts/reform/em/npa/config/audit/EntityAuditEventListener.java
src/main/java/uk/gov/hmcts/reform/em/npa/domain/AbstractAuditingEntity.java
src/test/java/uk/gov/hmcts/reform/em/npa/config/audit/AsyncEntityAuditEventWriterTest.java

https://tools.hmcts.net/jira/browse/EM-6067
use AbstractAuditingEntity

use AbstractAuditingEntity

---

build.gradle
config/owasp/dependency-check-suppressions.xml

EM-6103 fix-check all vulnerabilities

EM-6103 fix-check all vulnerabilities

---

build.gradle
database/Dockerfile

EM-6107 fix container registry

revert-to fix master

---

Jenkinsfile_CNP
src/contractTest/java/uk/gov/hmcts/reform/em/npa/IdamConsumerTest.java

EM-5213 add pact provider test

EM-5213 add pact provider test

---

build.gradle
src/aat/resources/application.yml
src/cftlib/resources/docker-compose-local.yml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/EM-6252
local setup

local setup

---

build.gradle
config/owasp/dependency-check-suppressions.xml
src/aat/java/uk/gov/hmcts/reform/em/npa/functional/MarkUpScenarios.java
src/aat/java/uk/gov/hmcts/reform/em/npa/functional/OpenIdConnectScenarios.java
src/aat/java/uk/gov/hmcts/reform/em/npa/functional/RedactionScenarios.java
src/aat/java/uk/gov/hmcts/reform/em/npa/smoke/SmokeTest.java

https://tools.hmcts.net/jira/browse/EM-6325
update serenity to 4.2.9

update serenity to 4.2.9

---

build.gradle

https://tools.hmcts.net/jira/browse/EM-6325
update package for okhttp mock

update package for okhttp mock

---

src/test/java/uk/gov/hmcts/reform/em/npa/config/security/SecurityUtilsTest.java
src/test/java/uk/gov/hmcts/reform/em/npa/info/BuildInfoTest.java
src/test/java/uk/gov/hmcts/reform/em/npa/redaction/ImageRedactionTest.java
src/test/java/uk/gov/hmcts/reform/em/npa/redaction/PdfRedactionTest.java
src/test/java/uk/gov/hmcts/reform/em/npa/rest/MarkUpResourceTest.java
src/test/java/uk/gov/hmcts/reform/em/npa/rest/WelcomeResourceTest.java
src/test/java/uk/gov/hmcts/reform/em/npa/service/CdamServiceTest.java
src/test/java/uk/gov/hmcts/reform/em/npa/service/impl/DmStoreDownloaderImplTest.java
src/test/java/uk/gov/hmcts/reform/em/npa/service/impl/MarkUpServiceImplTest.java

https://tools.hmcts.net/jira/browse/EM-6341
Tests updated to use JUnit5 annotations.
N/A

Tests updated to use JUnit5 annotations

---

build.gradle
src/aat/java/uk/gov/hmcts/reform/em/npa/functional/MarkUpScenariosTest.java
src/aat/java/uk/gov/hmcts/reform/em/npa/functional/OpenIdConnectScenariosTest.java
src/aat/java/uk/gov/hmcts/reform/em/npa/functional/RedactionScenariosTest.java

https://tools.hmcts.net/jira/browse/EM-6341
Functional Tests updated to use JUnit5 annotations.
N/A

Functional Tests updated to use JUnit5 annotations

---

build.gradle
src/aat/java/uk/gov/hmcts/reform/em/npa/functional/MarkUpScenariosTest.java
src/aat/java/uk/gov/hmcts/reform/em/npa/functional/OpenIdConnectScenariosTest.java
src/aat/java/uk/gov/hmcts/reform/em/npa/functional/RedactionScenariosTest.java

https://tools.hmcts.net/jira/browse/EM-6385
upgrade em-test-helper to 2.1.1
add retry extension

upgrade em-test-helper to 2.1.1

---

src/main/java/uk/gov/hmcts/reform/em/npa/redaction/PdfRedaction.java
src/main/resources/application.yaml

[EM-6414](https://tools.hmcts.net/jira/browse/EM-6414) add log for redaction coordinates.

EM-6414 add log

---

build.gradle
src/test/java/uk/gov/hmcts/reform/em/npa/redaction/PdfRedactionTest.java

https://tools.hmcts.net/jira/browse/EM-6589
Adding additional test coverage to PDFRedactions to satisfy sonar quality gate

EM-6589: PDFRedaction code coverage

---

src/main/java/uk/gov/hmcts/reform/em/npa/redaction/PdfRedaction.java
src/test/java/uk/gov/hmcts/reform/em/npa/redaction/PdfRedactionTest.java

[EM-6597](https://tools.hmcts.net/jira/browse/EM-6597)
font encoding issue INC5698057

EM-6597 font encoding issue INC5698057

---

src/contractTest/java/uk/gov/hmcts/reform/em/npa/NpaPactConsumerTest.java
src/contractTest/java/uk/gov/hmcts/reform/em/npa/NpaPactProviderTest.java

https://tools.hmcts.net/jira/browse/EM-6515
add pact consumer test for GET all markeups- /api/markups

EM-6515 get markups consumer pact test

---

src/contractTest/java/uk/gov/hmcts/reform/em/npa/consumer/IdamConsumerTest.java
src/contractTest/java/uk/gov/hmcts/reform/em/npa/consumer/NpaPactConsumerTest.java
src/contractTest/java/uk/gov/hmcts/reform/em/npa/provider/NpaPactProviderTest.java

refactor package structure for contract tests

refactor package structure for contract tests

---

src/contractTest/java/uk/gov/hmcts/reform/em/npa/consumer/NpaPactConsumerTest.java
src/contractTest/java/uk/gov/hmcts/reform/em/npa/provider/NpaPactProviderTest.java

[EM-6514](https://tools.hmcts.net/jira/browse/EM-6514) pact for markup update

EM-6514 pact for markup update

---

src/test/java/uk/gov/hmcts/reform/em/npa/TestSecurityConfiguration.java
src/test/java/uk/gov/hmcts/reform/em/npa/config/security/SecurityUtilsTest.java
src/test/java/uk/gov/hmcts/reform/em/npa/redaction/ImageRedactionTest.java
src/test/java/uk/gov/hmcts/reform/em/npa/redaction/PdfRedactionTest.java
src/test/java/uk/gov/hmcts/reform/em/npa/repository/IdamRepositoryTest.java
src/test/java/uk/gov/hmcts/reform/em/npa/rest/MarkUpResourceTest.java
src/test/java/uk/gov/hmcts/reform/em/npa/rest/RedactionResourceTest.java
src/test/java/uk/gov/hmcts/reform/em/npa/rest/errors/ExceptionTranslatorIntTest.java
src/test/java/uk/gov/hmcts/reform/em/npa/rest/errors/ExceptionTranslatorTestController.java
src/test/java/uk/gov/hmcts/reform/em/npa/service/CdamServiceTest.java
src/test/resources/config/application.yaml

https://tools.hmcts.net/jira/browse/EM-6787
remove code smells

remove code smells

---

src/test/java/uk/gov/hmcts/reform/em/npa/service/impl/DmStoreDownloaderImplTest.java

https://tools.hmcts.net/jira/browse/EM-6868
add unit test

add unit test
